/**
 * Template Service
 * Manages report templates for customizable export formats
 * Implements Story 4.5 requirements for template management
 */

import { v4 as uuidv4 } from 'uuid';
import {
  ReportTemplate,
  ReportType,
  TemplateLayout,
  BrandingOptions,
  ReportSection,
  CustomField
} from '../../../../shared/types/nlp.types';
import { ExportRepository } from '../repositories/export.repository';

export interface CreateTemplateRequest {
  name: string;
  description: string;
  templateType: ReportType;
  layout: TemplateLayout;
  branding?: BrandingOptions;
  sections: ReportSection[];
  customFields?: CustomField[];
}

export interface UpdateTemplateRequest {
  name?: string;
  description?: string;
  layout?: TemplateLayout;
  branding?: BrandingOptions;
  sections?: ReportSection[];
  customFields?: CustomField[];
}

export class TemplateService {
  private templateCache: Map<string, ReportTemplate>;
  private defaultTemplates: Map<ReportType, ReportTemplate>;

  constructor(private exportRepository: ExportRepository) {
    this.templateCache = new Map();
    this.defaultTemplates = new Map();
    this.initializeDefaultTemplates();
  }

  /**
   * Initialize default system templates
   */
  private initializeDefaultTemplates(): void {
    // Component List Template
    const componentListTemplate: ReportTemplate = {
      id: 'default-component-list',
      name: 'Standard Component List',
      description: 'Default template for component list exports',
      templateType: 'component_list',
      layout: {
        orientation: 'portrait',
        pageSize: 'A4',
        margins: { top: 20, bottom: 20, left: 15, right: 15 },
        includePageNumbers: true,
        includeTOC: false
      },
      branding: {
        headerText: 'Component List Report',
        footerText: 'Generated by Electrical Drawing Analysis System'
      },
      sections: [
        { id: 'header', name: 'Report Header', type: 'header', enabled: true, order: 1 },
        { id: 'summary', name: 'Component Summary', type: 'summary', enabled: true, order: 2 },
        { id: 'list', name: 'Component List', type: 'component_list', enabled: true, order: 3 },
        { id: 'footer', name: 'Report Footer', type: 'footer', enabled: true, order: 4 }
      ],
      isDefault: true,
      isSystem: true,
      createdAt: new Date(),
      updatedAt: new Date()
    };

    // Parts Order Template
    const partsOrderTemplate: ReportTemplate = {
      id: 'default-parts-order',
      name: 'Parts Order Template',
      description: 'Template for generating parts ordering lists',
      templateType: 'parts_order',
      layout: {
        orientation: 'landscape',
        pageSize: 'A4',
        margins: { top: 15, bottom: 15, left: 20, right: 20 },
        includePageNumbers: true,
        includeTOC: false
      },
      branding: {
        headerText: 'Parts Order List',
        footerText: 'Generated by Electrical Drawing Analysis System'
      },
      sections: [
        { id: 'header', name: 'Order Header', type: 'header', enabled: true, order: 1 },
        { id: 'summary', name: 'Order Summary', type: 'summary', enabled: true, order: 2 },
        { 
          id: 'list', 
          name: 'Parts List', 
          type: 'component_list', 
          enabled: true, 
          order: 3,
          config: { includePartNumbers: true, includeSuppliers: true }
        },
        { id: 'footer', name: 'Order Footer', type: 'footer', enabled: true, order: 4 }
      ],
      isDefault: true,
      isSystem: true,
      createdAt: new Date(),
      updatedAt: new Date()
    };

    // Technical Analysis Template
    const technicalAnalysisTemplate: ReportTemplate = {
      id: 'default-technical-analysis',
      name: 'Technical Analysis Report',
      description: 'Comprehensive technical analysis template',
      templateType: 'technical_analysis',
      layout: {
        orientation: 'portrait',
        pageSize: 'A4',
        margins: { top: 25, bottom: 25, left: 20, right: 20 },
        includePageNumbers: true,
        includeTOC: true
      },
      branding: {
        headerText: 'Technical Analysis Report',
        footerText: 'Confidential - Generated by Electrical Drawing Analysis System'
      },
      sections: [
        { id: 'header', name: 'Report Header', type: 'header', enabled: true, order: 1 },
        { id: 'summary', name: 'Executive Summary', type: 'summary', enabled: true, order: 2 },
        { id: 'list', name: 'Component Analysis', type: 'component_list', enabled: true, order: 3 },
        { id: 'visual', name: 'Visual Maps', type: 'visual_map', enabled: true, order: 4 },
        { id: 'xref', name: 'Cross References', type: 'cross_references', enabled: true, order: 5 },
        { id: 'footer', name: 'Report Footer', type: 'footer', enabled: true, order: 6 }
      ],
      isDefault: true,
      isSystem: true,
      createdAt: new Date(),
      updatedAt: new Date()
    };

    // Project Summary Template
    const projectSummaryTemplate: ReportTemplate = {
      id: 'default-project-summary',
      name: 'Project Summary Report',
      description: 'High-level project summary template',
      templateType: 'project_summary',
      layout: {
        orientation: 'portrait',
        pageSize: 'Letter',
        margins: { top: 20, bottom: 20, left: 20, right: 20 },
        includePageNumbers: true,
        includeTOC: false
      },
      branding: {
        headerText: 'Project Summary',
        footerText: 'Generated by Electrical Drawing Analysis System'
      },
      sections: [
        { id: 'header', name: 'Project Header', type: 'header', enabled: true, order: 1 },
        { id: 'summary', name: 'Project Overview', type: 'summary', enabled: true, order: 2 },
        { id: 'visual', name: 'Component Overview Maps', type: 'visual_map', enabled: true, order: 3 },
        { id: 'footer', name: 'Project Footer', type: 'footer', enabled: true, order: 4 }
      ],
      isDefault: true,
      isSystem: true,
      createdAt: new Date(),
      updatedAt: new Date()
    };

    // Store in default templates map
    this.defaultTemplates.set('component_list', componentListTemplate);
    this.defaultTemplates.set('parts_order', partsOrderTemplate);
    this.defaultTemplates.set('technical_analysis', technicalAnalysisTemplate);
    this.defaultTemplates.set('project_summary', projectSummaryTemplate);
  }

  /**
   * Get template by ID
   */
  public async getTemplate(templateId: string): Promise<ReportTemplate | null> {
    // Check cache first
    if (this.templateCache.has(templateId)) {
      return this.templateCache.get(templateId)!;
    }

    // Check default templates
    for (const template of this.defaultTemplates.values()) {
      if (template.id === templateId) {
        this.templateCache.set(templateId, template);
        return template;
      }
    }

    // Load from database
    const template = await this.exportRepository.getTemplate(templateId);
    if (template) {
      this.templateCache.set(templateId, template);
      return template;
    }

    return null;
  }

  /**
   * Get default template for report type
   */
  public async getDefaultTemplate(reportType: ReportType): Promise<ReportTemplate> {
    // Check in-memory defaults first
    const inMemoryDefault = this.defaultTemplates.get(reportType);
    if (inMemoryDefault) {
      return inMemoryDefault;
    }

    // Load from database
    const dbDefault = await this.exportRepository.getDefaultTemplate(reportType);
    if (dbDefault) {
      this.templateCache.set(dbDefault.id, dbDefault);
      return dbDefault;
    }

    // Fallback to basic template
    return this.createBasicTemplate(reportType);
  }

  /**
   * Create a basic template as fallback
   */
  private createBasicTemplate(reportType: ReportType): ReportTemplate {
    return {
      id: `basic-${reportType}`,
      name: `Basic ${reportType.replace('_', ' ')} Template`,
      description: 'Basic template for export',
      templateType: reportType,
      layout: {
        orientation: 'portrait',
        pageSize: 'A4',
        margins: { top: 20, bottom: 20, left: 20, right: 20 },
        includePageNumbers: true,
        includeTOC: false
      },
      branding: {
        headerText: 'Export Report',
        footerText: 'Generated Report'
      },
      sections: [
        { id: 'header', name: 'Header', type: 'header', enabled: true, order: 1 },
        { id: 'summary', name: 'Summary', type: 'summary', enabled: true, order: 2 },
        { id: 'list', name: 'Data', type: 'component_list', enabled: true, order: 3 },
        { id: 'footer', name: 'Footer', type: 'footer', enabled: true, order: 4 }
      ],
      isDefault: false,
      isSystem: false,
      createdAt: new Date(),
      updatedAt: new Date()
    };
  }

  /**
   * List all available templates
   */
  public async listTemplates(
    templateType?: ReportType
  ): Promise<ReportTemplate[]> {
    // Get database templates
    const dbTemplates = await this.exportRepository.listTemplates(templateType);
    
    // Merge with default templates
    const allTemplates: ReportTemplate[] = [];
    
    // Add default templates
    for (const [type, template] of this.defaultTemplates) {
      if (!templateType || type === templateType) {
        allTemplates.push(template);
      }
    }
    
    // Add database templates (excluding duplicates)
    for (const template of dbTemplates) {
      if (!allTemplates.find(t => t.id === template.id)) {
        allTemplates.push(template);
      }
    }
    
    return allTemplates;
  }

  /**
   * Create a new custom template
   */
  public async createTemplate(
    request: CreateTemplateRequest
  ): Promise<ReportTemplate> {
    // Validate sections
    this.validateSections(request.sections);

    const template: ReportTemplate = {
      id: uuidv4(),
      name: request.name,
      description: request.description,
      templateType: request.templateType,
      layout: request.layout,
      branding: request.branding || {},
      sections: request.sections,
      customFields: request.customFields,
      isDefault: false,
      isSystem: false,
      createdAt: new Date(),
      updatedAt: new Date()
    };

    // Save to database
    const savedTemplate = await this.exportRepository.saveTemplate(template);
    
    // Cache the template
    this.templateCache.set(savedTemplate.id, savedTemplate);
    
    return savedTemplate;
  }

  /**
   * Update an existing template
   */
  public async updateTemplate(
    templateId: string,
    request: UpdateTemplateRequest
  ): Promise<ReportTemplate | null> {
    const existing = await this.getTemplate(templateId);
    if (!existing) {
      return null;
    }

    // Don't allow updating system templates
    if (existing.isSystem) {
      throw new Error('Cannot update system templates');
    }

    // Validate sections if provided
    if (request.sections) {
      this.validateSections(request.sections);
    }

    const updated: ReportTemplate = {
      ...existing,
      name: request.name || existing.name,
      description: request.description || existing.description,
      layout: request.layout || existing.layout,
      branding: request.branding || existing.branding,
      sections: request.sections || existing.sections,
      customFields: request.customFields !== undefined ? request.customFields : existing.customFields,
      updatedAt: new Date()
    };

    // Update in database
    const savedTemplate = await this.exportRepository.updateTemplate(templateId, updated);
    
    // Update cache
    this.templateCache.set(templateId, savedTemplate);
    
    return savedTemplate;
  }

  /**
   * Delete a custom template
   */
  public async deleteTemplate(templateId: string): Promise<boolean> {
    const template = await this.getTemplate(templateId);
    if (!template) {
      return false;
    }

    // Don't allow deleting system templates
    if (template.isSystem) {
      throw new Error('Cannot delete system templates');
    }

    // Don't allow deleting default templates
    if (template.isDefault) {
      throw new Error('Cannot delete default template. Set another template as default first.');
    }

    // Delete from database
    const deleted = await this.exportRepository.deleteTemplate(templateId);
    
    // Remove from cache
    if (deleted) {
      this.templateCache.delete(templateId);
    }
    
    return deleted;
  }

  /**
   * Set a template as default for its type
   */
  public async setDefaultTemplate(templateId: string): Promise<boolean> {
    const template = await this.getTemplate(templateId);
    if (!template) {
      return false;
    }

    // Update in database
    const updated = await this.exportRepository.setDefaultTemplate(
      templateId,
      template.templateType
    );
    
    if (updated) {
      // Update cache
      template.isDefault = true;
      this.templateCache.set(templateId, template);
      
      // Update default templates map if not a system template
      if (!template.isSystem) {
        this.defaultTemplates.set(template.templateType, template);
      }
    }
    
    return updated;
  }

  /**
   * Validate template sections
   */
  private validateSections(sections: ReportSection[]): void {
    if (!sections || sections.length === 0) {
      throw new Error('Template must have at least one section');
    }

    const validTypes = ['header', 'summary', 'component_list', 'visual_map', 'cross_references', 'footer'];
    const orders = new Set<number>();

    for (const section of sections) {
      if (!validTypes.includes(section.type)) {
        throw new Error(`Invalid section type: ${section.type}`);
      }

      if (orders.has(section.order)) {
        throw new Error(`Duplicate section order: ${section.order}`);
      }
      orders.add(section.order);
    }
  }

  /**
   * Clone an existing template
   */
  public async cloneTemplate(
    templateId: string,
    newName: string
  ): Promise<ReportTemplate | null> {
    const original = await this.getTemplate(templateId);
    if (!original) {
      return null;
    }

    const cloned: ReportTemplate = {
      ...original,
      id: uuidv4(),
      name: newName,
      description: `Clone of ${original.name}`,
      isDefault: false,
      isSystem: false,
      createdAt: new Date(),
      updatedAt: new Date()
    };

    // Save to database
    const savedTemplate = await this.exportRepository.saveTemplate(cloned);
    
    // Cache the template
    this.templateCache.set(savedTemplate.id, savedTemplate);
    
    return savedTemplate;
  }

  /**
   * Get supported export formats for a template
   */
  public getSupportedFormats(template: ReportTemplate): string[] {
    const formats = ['pdf', 'csv', 'excel', 'json'];
    
    // Some templates might not support certain formats
    if (template.sections.some(s => s.type === 'visual_map' && s.enabled)) {
      // Visual maps are not suitable for CSV
      return formats.filter(f => f !== 'csv');
    }
    
    return formats;
  }

  /**
   * Clear template cache
   */
  public clearCache(): void {
    this.templateCache.clear();
  }
}