/**
 * Excel Export Handler
 * Generates Excel format exports for component reports
 * Implements Story 4.5 Excel export functionality
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import * as ExcelJS from 'exceljs';
import { 
  ComponentReport, 
  ComponentReportItem,
  ExportOptions,
  ReportTemplate,
  ComponentLocationMap
} from '../../../../shared/types/nlp.types';

export class ExcelExportHandler {
  private exportDirectory: string;

  constructor() {
    this.exportDirectory = process.env.EXPORT_DIR || '/tmp/electrical-exports';
  }

  /**
   * Generate Excel report file
   */
  async generateReport(
    report: ComponentReport,
    template: ReportTemplate | null,
    options: ExportOptions
  ): Promise<string> {
    const fileName = `component_report_${report.id}_${Date.now()}.xlsx`;
    const filePath = path.join(this.exportDirectory, fileName);

    // Ensure export directory exists
    await fs.mkdir(this.exportDirectory, { recursive: true });

    // Create workbook
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Electrical Drawing Analysis System';
    workbook.created = new Date();
    workbook.modified = new Date();

    // Apply branding if configured
    if (options.customBranding || template?.branding_config) {
      this.applyBranding(workbook, options.customBranding || template?.branding_config);
    }

    // Add summary sheet
    await this.addSummarySheet(workbook, report, template);

    // Add components sheet
    await this.addComponentsSheet(workbook, report.components, options);

    // Add cross-references sheet if available
    if (report.crossPageReferences && report.crossPageReferences.length > 0) {
      await this.addCrossReferencesSheet(workbook, report.crossPageReferences);
    }

    // Add visual maps sheet if available
    if (report.visualMaps && report.visualMaps.length > 0) {
      await this.addVisualMapsSheet(workbook, report.visualMaps);
    }

    // Add parts order sheet if requested
    if (options.includePartNumbers) {
      await this.addPartsOrderSheet(workbook, report.components);
    }

    // Save workbook
    await workbook.xlsx.writeFile(filePath);

    return filePath;
  }

  /**
   * Apply branding to workbook
   */
  private applyBranding(workbook: ExcelJS.Workbook, branding: any): void {
    if (branding) {
      const brandingConfig = typeof branding === 'string' ? JSON.parse(branding) : branding;
      
      workbook.properties = {
        ...workbook.properties,
        title: brandingConfig.headerText || 'Component Report',
        subject: 'Electrical Component Analysis',
        keywords: 'electrical, components, analysis',
        category: 'Technical Report',
        company: brandingConfig.company || '',
        comments: brandingConfig.footerText || 'Generated by Electrical Drawing Analysis System'
      };
    }
  }

  /**
   * Add summary sheet
   */
  private async addSummarySheet(
    workbook: ExcelJS.Workbook, 
    report: ComponentReport,
    template: ReportTemplate | null
  ): Promise<void> {
    const sheet = workbook.addWorksheet('Summary', {
      properties: { tabColor: { argb: 'FF0066CC' } }
    });

    // Title
    sheet.getCell('A1').value = 'Component Analysis Report Summary';
    sheet.getCell('A1').font = { bold: true, size: 16 };
    sheet.mergeCells('A1:E1');

    // Report metadata
    const metadataRows = [
      ['Report ID:', report.id],
      ['Session ID:', report.sessionId],
      ['Generated:', report.generatedAt.toISOString()],
      ['Report Type:', report.reportType],
      ['Export Format:', report.format]
    ];

    let row = 3;
    for (const [label, value] of metadataRows) {
      sheet.getCell(`A${row}`).value = label;
      sheet.getCell(`A${row}`).font = { bold: true };
      sheet.getCell(`B${row}`).value = value;
      row++;
    }

    // Component statistics
    row += 1;
    sheet.getCell(`A${row}`).value = 'Component Statistics';
    sheet.getCell(`A${row}`).font = { bold: true, size: 14 };
    sheet.mergeCells(`A${row}:C${row}`);
    row++;

    sheet.getCell(`A${row}`).value = 'Total Components:';
    sheet.getCell(`A${row}`).font = { bold: true };
    sheet.getCell(`B${row}`).value = report.componentSummary.totalComponents;
    row++;

    sheet.getCell(`A${row}`).value = 'Total Pages:';
    sheet.getCell(`A${row}`).font = { bold: true };
    sheet.getCell(`B${row}`).value = report.componentSummary.totalPages;
    row++;

    sheet.getCell(`A${row}`).value = 'Average Confidence:';
    sheet.getCell(`A${row}`).font = { bold: true };
    sheet.getCell(`B${row}`).value = report.componentSummary.confidenceAverage.toFixed(2);
    row++;

    sheet.getCell(`A${row}`).value = 'Processing Time (ms):';
    sheet.getCell(`A${row}`).font = { bold: true };
    sheet.getCell(`B${row}`).value = report.componentSummary.processingTime;
    row++;

    // Component breakdown by type
    row += 1;
    sheet.getCell(`A${row}`).value = 'Component Breakdown by Type';
    sheet.getCell(`A${row}`).font = { bold: true, size: 14 };
    sheet.mergeCells(`A${row}:C${row}`);
    row++;

    sheet.getCell(`A${row}`).value = 'Type';
    sheet.getCell(`B${row}`).value = 'Count';
    sheet.getCell(`C${row}`).value = 'Percentage';
    sheet.getRow(row).font = { bold: true };
    sheet.getRow(row).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE0E0E0' }
    };
    row++;

    const totalComponents = report.componentSummary.totalComponents;
    for (const [type, count] of Object.entries(report.componentSummary.componentsByType)) {
      sheet.getCell(`A${row}`).value = type;
      sheet.getCell(`B${row}`).value = count;
      sheet.getCell(`C${row}`).value = `${((count / totalComponents) * 100).toFixed(1)}%`;
      row++;
    }

    // Auto-fit columns
    sheet.columns.forEach((column, index) => {
      if (index < 5) {
        column.width = 25;
      }
    });
  }

  /**
   * Add components sheet
   */
  private async addComponentsSheet(
    workbook: ExcelJS.Workbook,
    components: ComponentReportItem[],
    options: ExportOptions
  ): Promise<void> {
    const sheet = workbook.addWorksheet('Components', {
      properties: { tabColor: { argb: 'FF00CC66' } }
    });

    // Build headers
    const headers = ['ID', 'Type', 'Description', 'Page', 'Document', 'Zone', 'X', 'Y'];

    if (options.includeTechnicalSpecs) {
      headers.push('Value', 'Unit', 'Tolerance', 'Rating', 'Package', 'Manufacturer');
    }

    if (options.includePartNumbers) {
      headers.push('Part Number', 'Supplier', 'Quantity', 'Unit Price');
    }

    if (options.includeConfidenceScores) {
      headers.push('Confidence');
    }

    headers.push('Related Components', 'Notes');

    // Add headers
    sheet.addRow(headers);
    sheet.getRow(1).font = { bold: true };
    sheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF4472C4' }
    };

    // Add component data
    for (const component of components) {
      const row: any[] = [
        component.id,
        component.type,
        component.description || '',
        component.location.pageNumber,
        component.location.documentId,
        component.location.zone || '',
        component.location.coordinates.x,
        component.location.coordinates.y
      ];

      if (options.includeTechnicalSpecs) {
        row.push(
          component.specifications?.value || '',
          component.specifications?.unit || '',
          component.specifications?.tolerance || '',
          component.specifications?.rating || '',
          component.specifications?.package || '',
          component.specifications?.manufacturer || ''
        );
      }

      if (options.includePartNumbers) {
        row.push(
          component.partInformation?.partNumber || '',
          component.partInformation?.supplier || '',
          component.partInformation?.quantity || 1,
          component.partInformation?.unitPrice || ''
        );
      }

      if (options.includeConfidenceScores) {
        row.push(component.confidence.toFixed(2));
      }

      row.push(
        component.relatedComponents?.join(', ') || '',
        component.specifications?.customProperties?.notes || ''
      );

      sheet.addRow(row);
    }

    // Apply filters
    sheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: components.length + 1, column: headers.length }
    };

    // Format columns
    sheet.columns.forEach((column, index) => {
      column.width = 15;
      if (index === 2 || index === headers.length - 2 || index === headers.length - 1) {
        column.width = 30; // Wider for description, related components, and notes
      }
    });

    // Apply conditional formatting for confidence scores if included
    if (options.includeConfidenceScores) {
      const confidenceColumn = headers.indexOf('Confidence') + 1;
      const highConfidenceRule = {
        type: 'cellIs',
        operator: 'greaterThan',
        formulae: ['0.8'],
        style: {
          fill: {
            type: 'pattern',
            pattern: 'solid',
            bgColor: { argb: 'FF90EE90' }
          }
        }
      };

      const lowConfidenceRule = {
        type: 'cellIs',
        operator: 'lessThan',
        formulae: ['0.5'],
        style: {
          fill: {
            type: 'pattern',
            pattern: 'solid',
            bgColor: { argb: 'FFFFA500' }
          }
        }
      };

      sheet.addConditionalFormatting({
        ref: `${String.fromCharCode(64 + confidenceColumn)}2:${String.fromCharCode(64 + confidenceColumn)}${components.length + 1}`,
        rules: [highConfidenceRule as any, lowConfidenceRule as any]
      });
    }
  }

  /**
   * Add cross-references sheet
   */
  private async addCrossReferencesSheet(
    workbook: ExcelJS.Workbook,
    crossReferences: any[]
  ): Promise<void> {
    const sheet = workbook.addWorksheet('Cross References', {
      properties: { tabColor: { argb: 'FFCC6600' } }
    });

    const headers = [
      'Source Component',
      'Source Page',
      'Target Component',
      'Target Page',
      'Reference Type',
      'Connection Type',
      'Confidence'
    ];

    sheet.addRow(headers);
    sheet.getRow(1).font = { bold: true };
    sheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFCC6600' }
    };

    for (const ref of crossReferences) {
      sheet.addRow([
        ref.sourceComponentId,
        ref.sourcePageNumber,
        ref.targetComponentId,
        ref.targetPageNumber,
        ref.referenceType,
        ref.connectionType || '',
        ref.confidence?.toFixed(2) || ''
      ]);
    }

    sheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: crossReferences.length + 1, column: headers.length }
    };

    sheet.columns.forEach(column => {
      column.width = 20;
    });
  }

  /**
   * Add visual maps sheet
   */
  private async addVisualMapsSheet(
    workbook: ExcelJS.Workbook,
    visualMaps: ComponentLocationMap[]
  ): Promise<void> {
    const sheet = workbook.addWorksheet('Visual Maps', {
      properties: { tabColor: { argb: 'FFCC00CC' } }
    });

    const headers = [
      'Page',
      'Document',
      'Component Count',
      'Width',
      'Height',
      'Scale'
    ];

    sheet.addRow(headers);
    sheet.getRow(1).font = { bold: true };
    sheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFCC00CC' }
    };

    for (const map of visualMaps) {
      sheet.addRow([
        map.pageNumber,
        map.documentId,
        map.components.length,
        map.dimensions.width,
        map.dimensions.height,
        map.scale
      ]);
    }

    sheet.columns.forEach(column => {
      column.width = 15;
    });
  }

  /**
   * Add parts order sheet
   */
  private async addPartsOrderSheet(
    workbook: ExcelJS.Workbook,
    components: ComponentReportItem[]
  ): Promise<void> {
    const sheet = workbook.addWorksheet('Parts Order (BOM)', {
      properties: { tabColor: { argb: 'FFFF0000' } }
    });

    // Group components by part number
    const partsMap = new Map<string, {
      partNumber: string;
      description: string;
      manufacturer: string;
      supplier: string;
      quantity: number;
      unitPrice: number;
      totalPrice: number;
      componentRefs: string[];
    }>();

    for (const component of components) {
      if (component.partInformation?.partNumber) {
        const partNumber = component.partInformation.partNumber;
        
        if (partsMap.has(partNumber)) {
          const part = partsMap.get(partNumber)!;
          part.quantity += component.partInformation.quantity || 1;
          part.componentRefs.push(component.id);
          part.totalPrice = part.quantity * part.unitPrice;
        } else {
          partsMap.set(partNumber, {
            partNumber,
            description: component.description,
            manufacturer: component.partInformation.manufacturer || '',
            supplier: component.partInformation.supplier || '',
            quantity: component.partInformation.quantity || 1,
            unitPrice: component.partInformation.unitPrice || 0,
            totalPrice: (component.partInformation.quantity || 1) * (component.partInformation.unitPrice || 0),
            componentRefs: [component.id]
          });
        }
      }
    }

    const headers = [
      'Part Number',
      'Description',
      'Manufacturer',
      'Supplier',
      'Quantity',
      'Unit Price',
      'Total Price',
      'Component References'
    ];

    sheet.addRow(headers);
    sheet.getRow(1).font = { bold: true };
    sheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFFF0000' }
    };

    let totalCost = 0;
    for (const part of partsMap.values()) {
      sheet.addRow([
        part.partNumber,
        part.description,
        part.manufacturer,
        part.supplier,
        part.quantity,
        part.unitPrice,
        part.totalPrice,
        part.componentRefs.join(', ')
      ]);
      totalCost += part.totalPrice;
    }

    // Add total row
    const totalRow = sheet.addRow([
      'TOTAL',
      '',
      '',
      '',
      '',
      '',
      totalCost,
      ''
    ]);
    totalRow.font = { bold: true };
    totalRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFFFCC00' }
    };

    // Format price columns as currency
    const priceColumns = [6, 7]; // Unit Price and Total Price columns
    priceColumns.forEach(colNum => {
      for (let row = 2; row <= sheet.rowCount; row++) {
        const cell = sheet.getCell(row, colNum);
        if (cell.value && typeof cell.value === 'number') {
          cell.numFmt = '$#,##0.00';
        }
      }
    });

    sheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: partsMap.size + 1, column: headers.length }
    };

    sheet.columns.forEach((column, index) => {
      column.width = index === 1 || index === 7 ? 30 : 15;
    });
  }
}